### ISSUE TITLE
[test] 스크랩 기능 검증

### ISSUE THREAD

**Issue by sm-amoled** [sm-amoled/InsightCapture#10]
## 작업에 대한 간단한 설명
- URL을 통한 외부 페이지를 스크랩하는 기능에 대한 검증이 필요함

## TODO
- [x] Link Presentation 프레임워크를 통해 URL을 받아오는 기능 검증
- [x] 받아온 데이터를 파싱해, 원하는 형태로 편집하는 기능 검증
- [x] 이미지 업로드 기능 검증
- [x] share extension에서 코어데이터로 저장 및 메인 앱에서 불러오기 기능 검증
- [x] 공유하기로 input되는 데이터 구분 기능 검증

## Optional
- 작업 전 숙지 사항
