### ISSUE TITLE
[feat] 기록 확인 페이지 뷰 UI 구현

### ISSUE THREAD

**Issue by sm-amoled** [sm-amoled/InsightCapture#11]
## 작업에 대한 간단한 설명
- 기록 확인 페이지에 대한 UI 구현이 필요합니다.
<img width="676" alt="image" src="https://user-images.githubusercontent.com/39216546/229756073-97e6e34c-a9e3-47b3-a534-78618f729f6f.png">

## TODO
- [x] UI layout 구현
- [x] 사진 확인하기 뷰 구현
- [x] CoreData 적용 및 수정, 삭제 기능 구현

## Optional
- 작업 전 숙지 사항
