### ISSUE TITLE
[feat] 공유하기 뷰 UI 구현

### ISSUE THREAD

**Issue by sm-amoled** [sm-amoled/InsightCapture#12]
## 작업에 대한 간단한 설명
- 

## TODO
- [x] Share Extension 추가
- [x] 들어오는 데이터 종류에 따라 UI 다르게 그리기
- [x] Link Presentation으로 링크에서 데이터 가져오는 기능 추가

## Optional
- 작업 전 숙지 사항
