### ISSUE TITLE
[design] 기록 확인 뷰 UI 구상

### ISSUE THREAD

**Issue by sm-amoled** [sm-amoled/InsightCapture#2]
## 작업에 대한 간단한 설명
- 남긴 인사이트들에 대한 기록을 확인할 수 있는 화면의 UI 구상

## TODO
- [x] 기록의 보여지는 형태
- [x] 리스트에 담을 내용
- [x] 리스트 외 화면 구성 요소

## Optional
- 작업 전 숙지 사항
