### ISSUE TITLE
[feat] 마이페이지 뷰 UI 및 로직 구현하기

### ISSUE THREAD

**Issue by sm-amoled** [sm-amoled/InsightCapture#23]
## 작업에 대한 간단한 설명
- 마이페이지 뷰의 UI와 로직을 구현합니다.
<img width="310" alt="image" src="https://github.com/sm-amoled/InsightCapture/assets/39216546/20d0adc6-e156-4139-92fa-59f35f28a27a">

## TODO
- [x] 나의 기록 
  - [x] 기록된 인사이트 통계 산출하기
  - [x] 첫 방문 기록, 방문 횟수 기록 구현하기
  - [x] 나의 기록 UI 구현하기
- [x] 이용 안내
  - [x] 공지사항 추가하기
- [x] 기능 건의
  - [x] 기능 건의 UI 작성하기
- [ ] 약관 및 정책
  - [ ] 약관 및 정책 UI 구현하기

## Optional
- 개인정보 처리정책, 이용 약관 내용 어떻게 넣으면 되는지 찾아봐야함!
- 기능 건의는 추후에는 파이어베이스 등의 서버를 붙여서 구현하겠지만, 
  지금은 메일 주소를 전달해서 임시로 창구를 구현하기! (메일 제목과 내용 예시로 보여주어 부담 덜어주는 방식 생각해보자.)

**Comment by sm-amoled** [comment]
약관 및 정책에 들어갈 내용을 지금 탑재하는게 맞는지에 대해 의문이 들어서, 약관 및 정책은 지금 버전에서는 제외하고 진행하는 방향으로 계획중임.

이후에 파이어베이스 등을 추가하면서 개인정보 제공 동의 등이 필요한 때가 되면 해당 내용을 추가할 수 있도록 기억해두기!
