### ISSUE TITLE
[feat] 입력 내용 없을 때 자동 입력 내용 추가

### ISSUE THREAD

**Issue by sm-amoled** [sm-amoled/InsightCapture#25]
## 작업에 대한 간단한 설명
- 사용자가 내용을 입력하지 않았을 때 자동으로 미리 정의해둔 데이터를 넣어주기

## TODO
- [x] 어떤 데이터 넣어줄지 리스트 작성하기
- [x] 제목 데이터 리스트 만들기
- [x] 랜덤으로 데이터 넣기 기능 구현

## Optional
- 작업 전 숙지 사항
