### ISSUE TITLE
[feat] misc task

### ISSUE THREAD

**Issue by sm-amoled** [sm-amoled/InsightCapture#26]
## 작업에 대한 간단한 설명
- 개발 중 지나친 여러 테스크에 대한 보완 작업을 수행하기

## TODO
- [ ] 메인 앱
  - [ ] 페이지 뷰
    - [x] 이미지 비율 조정하기
    - [ ] 페이지 내 버튼 선명하게 보이도록 가시성 수정하기
  - [ ] 리스트/카드 뷰
    - [ ] 버튼 작동하도록 기능 넣기
  - [ ] 추가하기
    - [ ] 저장 조건 넣기
  - [ ] 마이페이지
    - [ ] 영감 소스(출처) 잘 들어오는지 확인하기
- [ ] 공유 앱
  - [ ] 플레이스 홀더가 잘 들어오지 않는 문제가 있음

## Optional
더 할 수 있으면 시도할만한 작업
- ActionSheet의 목록에 share 하는 것을 추가할 수 있는지 확인해보기
- 태그 기능 추가하기
- 메인 리스트의 올드한 디자인 수정하기
