### ISSUE TITLE
[invest] 다양한 Question에 대한 조사 진행

### ISSUE THREAD

**Issue by sm-amoled** [sm-amoled/InsightCapture#6]
## 작업에 대한 간단한 설명
- 앱 디자인 전, 기획을 위한 리서치 과정

## TODO
- [x] 중요한 질문
  - [x] 사람들은 지금은 인사이트를 어떻게 정리하지?
  - [x] 사람들은 어떤 것에 대한 인사이트를 수집하지?
  - [x] 어디에서 인사이트를 수집하지? 인식하지 못하고 많은 인사이트를 받는 곳은 어디일까?

- [x] 유용한 질문
  - [x] 인사이트를 다시 확인하는 주기, 시점은 언제이지? 언제 다시 인사이트를 확인하려 할까? 인사이트가 나에게 도움을 주는 시점은?
  - [x] 어떤 형태로 인사이트 기록들을 보여줘야 제일 효율적이고, 계속 기록을 남기고 싶어할까?
- [x] 궁금한 질문
  - [x] 인사이트를 제공하는 것을 컨텐츠로 하는 플랫폼은 주로 어디일까?

## Optional
- 작업 전 숙지 사항

**Comment by sm-amoled** [comment]
Notion에 정리 완료
