### ISSUE TITLE
[test] 공유하기 데이터의 종류에 따른 뷰 분리 검증

### ISSUE THREAD

**Issue by sm-amoled** [sm-amoled/InsightCapture#7]
## 작업에 대한 간단한 설명
- 공유하기를 통해 넘어오는 데이터가 텍스트/URL/이미지 등 다양한 형태로 올텐데, 이에 따라 여러 뷰를 선택적으로 제공할 수 있는지 확인이 필요함

## TODO
- [x] 공유하기를 통해 앱의 특정 페이지로 진입 검증
- [x] 넘어오는 데이터를 식별할 수 있는지 검증
- [x] 데이터에 따라 뷰를 선택할 수 있는 로직 검증

## Optional
- 작업 전 숙지 사항
