### ISSUE TITLE
[invest] 앱의 핵심 가치 설정

### ISSUE THREAD

**Issue by sm-amoled** [sm-amoled/InsightCapture#9]
## 작업에 대한 간단한 설명
- 만드는 앱이 "누구"를 "어떤 상태로 만들기"위해 "어떤 솔루션"을 제공하고자 하는지 설정하여, 앱의 방향성과 가치관을 결정하기

## TODO
- [x] 타겟 유저 선정
- [x] 유저에게 제공할 효용 설정
- [x] 효용 제공을 위한 솔루션 컨셉 설정
- [x] 앱의 방향성과 가치관 정리하기

## Optional
- 작업 전 숙지 사항

**Comment by sm-amoled** [comment]
노션에 정리 완료
